import type { Module } from "./types";

export const DEFAULT_MODULES: Module[] = [
  {
    id:           "ai-engine",
    name:         "AI Engine",
    icon:         "🤖",
    description:  "Core language model powering all AI responses and generation",
    enabled:      true,
    status:       "Active",
    accentColor:  "#7c5ce7",
    version:      "3.2.1",
    dependencies: [],
    permissions:  ["network", "storage", "compute"],
    settings: {
      model:        "gpt-4o",
      temperature:  0.7,
      maxTokens:    2048,
      systemPrompt: "You are Apex, a powerful AI assistant.",
      streamMode:   true,
    },
    settingsSchema: [
      { key: "model",        label: "Model",            type: "dropdown", options: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "claude-3-5-sonnet"] },
      { key: "temperature",  label: "Temperature (0–1)", type: "number",   min: 0,   max: 1   },
      { key: "maxTokens",    label: "Max Tokens",        type: "number",   min: 256, max: 8192 },
      { key: "systemPrompt", label: "System Prompt",     type: "textarea", placeholder: "Enter system prompt..." },
      { key: "streamMode",   label: "Streaming Mode",    type: "toggle" },
    ],
  },
  {
    id:           "dm-system",
    name:         "DM System",
    icon:         "💬",
    description:  "Direct message automation, tone control, and reply scheduling",
    enabled:      true,
    status:       "Active",
    accentColor:  "#00cec9",
    version:      "2.1.0",
    dependencies: ["ai-engine"],
    permissions:  ["network", "contacts", "notifications"],
    settings: {
      autoReply:      true,
      tone:           "Friendly",
      replyDelay:     1.5,
      maxDMsPerHour:  60,
      signature:      "",
    },
    settingsSchema: [
      { key: "autoReply",     label: "Auto Reply",          type: "toggle" },
      { key: "tone",          label: "Tone",                type: "dropdown", options: ["Friendly", "Professional", "Casual", "Assertive", "Empathetic"] },
      { key: "replyDelay",    label: "Reply Delay (sec)",   type: "number",   min: 0, max: 60  },
      { key: "maxDMsPerHour", label: "Max DMs / Hour",      type: "number",   min: 1, max: 300 },
      { key: "signature",     label: "Signature",           type: "text",     placeholder: "— Sent via Apex" },
    ],
  },
  {
    id:           "voice-system",
    name:         "Voice System",
    icon:         "🎙️",
    description:  "Text-to-speech and voice cloning powered by ElevenLabs",
    enabled:      false,
    status:       "Disabled",
    accentColor:  "#e056fd",
    version:      "1.4.2",
    dependencies: ["ai-engine"],
    permissions:  ["microphone", "audio", "storage"],
    settings: {
      voiceId:      "Rachel",
      speed:        1.0,
      language:     "English",
      autoCaptions: false,
      stability:    0.75,
    },
    settingsSchema: [
      { key: "voiceId",      label: "Voice",           type: "dropdown", options: ["Rachel", "Adam", "Domi", "Elli", "Josh", "Arnold"] },
      { key: "speed",        label: "Speed (0.5–2.0)", type: "number",   min: 0.5, max: 2.0 },
      { key: "language",     label: "Language",        type: "dropdown", options: ["English", "Spanish", "French", "German", "Japanese", "Portuguese"] },
      { key: "stability",    label: "Stability (0–1)", type: "number",   min: 0,   max: 1   },
      { key: "autoCaptions", label: "Auto Captions",   type: "toggle" },
    ],
  },
  {
    id:           "battle-mode",
    name:         "Battle Mode",
    icon:         "⚔️",
    description:  "Head-to-head AI debate and competitive response battles",
    enabled:      true,
    status:       "Active",
    accentColor:  "#d63031",
    version:      "2.0.0",
    dependencies: ["ai-engine"],
    permissions:  ["compute", "network"],
    settings: {
      difficulty:       "Hard",
      roundsPerMatch:   3,
      judgeModel:       "gpt-4o",
      timeoutSeconds:   30,
      enableSpectators: true,
    },
    settingsSchema: [
      { key: "difficulty",       label: "Difficulty",       type: "dropdown", options: ["Easy", "Medium", "Hard", "Legendary"] },
      { key: "roundsPerMatch",   label: "Rounds per Match", type: "number",   min: 1,  max: 10  },
      { key: "judgeModel",       label: "Judge Model",      type: "dropdown", options: ["gpt-4o", "gpt-4o-mini", "claude-3-5-sonnet"] },
      { key: "timeoutSeconds",   label: "Timeout (sec)",    type: "number",   min: 10, max: 120 },
      { key: "enableSpectators", label: "Enable Spectators", type: "toggle" },
    ],
  },
  {
    id:           "hive-mode",
    name:         "Hive Mode",
    icon:         "🐝",
    description:  "Multi-agent swarm intelligence — agents collaborate as a hive",
    enabled:      false,
    status:       "Coming Soon",
    accentColor:  "#fdcb6e",
    version:      "0.9.0-beta",
    dependencies: ["ai-engine", "dm-system"],
    permissions:  ["compute", "network", "storage"],
    settings: {
      nodeCount:      5,
      syncIntervalMs: 500,
      strategy:       "Consensus",
      maxDepth:       3,
      broadcastToAll: false,
    },
    settingsSchema: [
      { key: "nodeCount",      label: "Agent Nodes",            type: "number",   min: 2,   max: 32   },
      { key: "syncIntervalMs", label: "Sync Interval (ms)",     type: "number",   min: 100, max: 5000 },
      { key: "strategy",       label: "Strategy",               type: "dropdown", options: ["Consensus", "Majority Vote", "Leader-Follower", "Parallel Race"] },
      { key: "maxDepth",       label: "Max Reasoning Depth",    type: "number",   min: 1,   max: 10   },
      { key: "broadcastToAll", label: "Broadcast to All Nodes", type: "toggle" },
    ],
  },
  {
    id:           "screenshot-ai",
    name:         "Screenshot AI",
    icon:         "📸",
    description:  "Capture, analyze, and caption screenshots with AI vision",
    enabled:      true,
    status:       "Active",
    accentColor:  "#00b894",
    version:      "1.2.3",
    dependencies: ["ai-engine"],
    permissions:  ["camera", "storage", "network"],
    settings: {
      quality:      "High",
      format:       "PNG",
      autoCaption:  true,
      visionModel:  "gpt-4o",
      saveHistory:  true,
    },
    settingsSchema: [
      { key: "quality",     label: "Quality",       type: "dropdown", options: ["Low", "Medium", "High", "Ultra"] },
      { key: "format",      label: "Format",        type: "dropdown", options: ["PNG", "JPEG", "WebP"] },
      { key: "visionModel", label: "Vision Model",  type: "dropdown", options: ["gpt-4o", "gpt-4o-mini"] },
      { key: "autoCaption", label: "Auto Caption",  type: "toggle" },
      { key: "saveHistory", label: "Save History",  type: "toggle" },
    ],
  },
];
