/**
 * Apex AI OS — Core Database Schema
 *
 * Two tables power the AI OS foundation:
 *   apex_os_projects    — Project model (apps generated by the OS)
 *   apex_os_memory_logs — Interaction memory log for the self-improving system
 */

import {
  pgTable,
  serial,
  text,
  timestamp,
  jsonb,
  integer,
  pgEnum,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

// ── Enums ─────────────────────────────────────────────────────────────────────

export const projectStatusEnum = pgEnum("apex_os_project_status", [
  "active",
  "building",
  "ready",
  "error",
  "archived",
]);

export const memoryLogTypeEnum = pgEnum("apex_os_memory_log_type", [
  "prompt",
  "error",
  "workflow",
  "fix",
  "ai_output",
  "improvement",
]);

// ── Shared TypeScript types ────────────────────────────────────────────────────

export interface OsWorkflowStep {
  id: string;
  action: string;
  input?: string;
  output?: string;
  conditions?: string;
}

export interface OsWorkflow {
  id: string;
  name: string;
  description: string;
  triggers: string[];
  steps: OsWorkflowStep[];
  status: "idle" | "running" | "complete" | "error";
  createdAt: string;
  lastRunAt?: string;
}

export interface OsProjectPlan {
  goal: string;
  features: string[];
  pages: string[];
  tech_stack: string[];
  database_schema?: { table: string; fields: string[] }[];
  api_routes?: string[];
}

export interface WorkflowExecutionLog {
  workflowId: string;
  workflowName: string;
  startedAt: string;
  completedAt?: string;
  success: boolean;
  stepResults: {
    stepId: string;
    action: string;
    status: "done" | "error" | "skipped";
    output?: string;
    durationMs: number;
  }[];
  totalDurationMs: number;
  error?: string;
}

// ── apex_os_projects ──────────────────────────────────────────────────────────

export const apexOsProjectsTable = pgTable("apex_os_projects", {
  id: serial("id").primaryKey(),

  // Identity
  sessionId:   text("session_id"),
  name:        text("name").notNull(),
  description: text("description"),
  prompt:      text("prompt").notNull(),

  // Status
  status: text("status").notNull().default("active"),

  // Generated content
  plan:          jsonb("plan").$type<OsProjectPlan>(),
  generatedCode: text("generated_code"),
  previewHtml:   text("preview_html"),
  workflows:     jsonb("workflows").$type<OsWorkflow[]>().notNull().default([]),

  // Telemetry
  buildCount:  integer("build_count").notNull().default(0),
  editCount:   integer("edit_count").notNull().default(0),
  runCount:    integer("run_count").notNull().default(0),
  errorCount:  integer("error_count").notNull().default(0),
  tokensUsed:  integer("tokens_used").notNull().default(0),

  // Execution history (last 20 workflow runs)
  executionHistory: jsonb("execution_history")
    .$type<WorkflowExecutionLog[]>()
    .notNull()
    .default([]),

  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertApexOsProjectSchema = createInsertSchema(apexOsProjectsTable).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export type ApexOsProject = typeof apexOsProjectsTable.$inferSelect;
export type InsertApexOsProject = z.infer<typeof insertApexOsProjectSchema>;

// ── apex_os_memory_logs ────────────────────────────────────────────────────────

export const apexOsMemoryLogsTable = pgTable("apex_os_memory_logs", {
  id: serial("id").primaryKey(),

  projectId: integer("project_id"),
  sessionId: text("session_id"),

  // Log type: prompt | error | workflow | fix | ai_output | improvement
  type: text("type").notNull(),

  // Raw content (prompt text, error message, workflow JSON, fix diff, etc.)
  content: text("content").notNull(),

  // Structured metadata depends on type
  metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}),

  // AI-extracted insight (populated by the self-improving system)
  insight: text("insight"),

  // Outcome tracking
  success:    jsonb("success").$type<boolean | null>().default(null),
  durationMs: integer("duration_ms"),

  timestamp: timestamp("timestamp", { withTimezone: true }).notNull().defaultNow(),
});

export const insertApexOsMemoryLogSchema = createInsertSchema(apexOsMemoryLogsTable).omit({
  id: true,
  timestamp: true,
});

export type ApexOsMemoryLog = typeof apexOsMemoryLogsTable.$inferSelect;
export type InsertApexOsMemoryLog = z.infer<typeof insertApexOsMemoryLogSchema>;
